PEER-255 Add docker-compose config for user-db and user-service
CS3219-AY2425S1/cs3219-ay2425s1-project-g16 pull request #33
Opened 2024-10-03 10:33 UTC by SeeuSim

2024-10-03 14:43 UTC, TabrizPlv requested changes

2024-10-03 14:43 UTC, TabrizPlv commented on backend/user/express.Dockerfile
> +COPY --from=build /data/question-express/.env .env
Copying `env` files in image may lead to security vulnerabilities.
Also, copying here is not necessary as you are inserting the `env` file in `docker-compose`

2024-10-03 14:43 UTC, TabrizPlv commented on backend/user/express.Dockerfile
>  WORKDIR /data/question-express
Replace all `question` with `user`

2024-10-04 03:39 UTC, SeeuSim commented on backend/user/express.Dockerfile
> +COPY --from=build /data/question-express/.env .env
it needs it for the `env-cmd` method, otherwise you can use `dotenv` to read from the environment itself

2024-10-05 16:54 UTC, TabrizPlv approved these changes
LGTM

2024-10-06 01:54 UTC, merged