PEER-232: Match Initiation UI
CS3219-AY2425S1/cs3219-ay2425s1-project-g16 pull request #44
Opened 2024-10-16 15:06 UTC by cyiting

To test:
Go to: backend/matching/src/services/get-match-items.ts
Add a random roomId and 1<= questionId <= 20

e.g. {
    roomId: '12345',
    questionId: '4',
  };

2024-10-16 15:17 UTC, cyiting commented on frontend/src/routes/match/match-form.tsx
> +                        <MultiSelectorInput placeholder='Select topic(s)' />
TO DO: add radix ui caret sort icon if possible

2024-10-16 16:28 UTC, SeeuSim requested changes
Lgtm, just test with integrated docker-compose config and see if nginx can proxy the ws connections

2024-10-16 16:28 UTC, SeeuSim commented on frontend/.env.docker
> +VITE_COLLAB_SERVICE=http://host.docker.internal:9004
add Matching Service

2024-10-16 16:28 UTC, SeeuSim commented on frontend/nginx.conf.template
> +        proxy_set_header X-Forwarded-Proto $scheme;
Has this been tested? i.e. ws proxy for socket.io

2024-10-16 16:28 UTC, SeeuSim commented on frontend/src/routes/match/match-form.tsx
> +      navigate(ROUTES.WAITING_ROOM, { state: { socketPort } });
maybe just open a modal for D4 instead of navigating here

2024-10-17 18:09 UTC, SeeuSim approved these changes

2024-10-20 05:46 UTC, merged